# Generated by Django 4.1.6 on 2023-03-14 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchList',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingInWatchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
